name: ciencia-de-dados
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - openpyxl
  - xlrd
  - scikit-learn
  - pytorch
  - rise
  - jupyterthemes
  - pip:
    - jupyter-contrib-nbextensions
